#!/usr/bin/env bash
# Link this project directory so ecpi is available as /usr/local/bin/ecpi.
# Requires sudo to create the symlink in /usr/local/bin.

set -e
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
LINK_PATH="/usr/local/bin/ecpi"
TARGET="${SCRIPT_DIR}/ecpi"

if [[ ! -x "$TARGET" ]]; then
  echo "Making ecpi executable."
  chmod +x "$TARGET"
fi

# ecpi finds ecpi_lib by __file__ directory, so it must be run from the project dir.
# Install a wrapper in /usr/local/bin that runs the script from SCRIPT_DIR.
WRAPPER="#!/usr/bin/env bash
# Wrapper generated by link-ecpi.sh - runs ecpi from the project directory.
ECPI_DIR='${SCRIPT_DIR}'
exec \"\$ECPI_DIR/ecpi\" \"\$@\"
"

if [[ -e "$LINK_PATH" ]]; then
  echo "Updating existing $LINK_PATH"
else
  echo "Installing ecpi into /usr/local/bin (sudo required)."
fi
printf '%s' "$WRAPPER" | sudo tee "$LINK_PATH" > /dev/null
sudo chmod +x "$LINK_PATH"
echo "Done. Run: ecpi <package>"
echo "  $LINK_PATH -> $TARGET"
